### ISSUE TITLE
亲，1.01版本，在NuGet上没有Html.AjaxPager扩展方法呢

### ISSUE THREAD

**Issue by yongshuai1573** [Webdiyer/MvcPagerCore#3]
亲，1.01版本，在NuGet上没有Html.AjaxPager扩展方法呢

**Comment by Webdiyer** [comment]
已经改为Ajax.Pager

**Comment by yongshuai1573** [comment]
要引用什么名称空间么？Ajax.Pager也没有在1.01版中发现，谢谢。

**Comment by Webdiyer** [comment]
> 要引用什么名称空间么？Ajax.Pager也没有在1.01版中发现，谢谢。

晕，1.01版？那太老了，源代码也找不到了，干嘛用那么老的版本？？

**Comment by yongshuai1573** [comment]
NutGet中安装的，不是大神你上传的么？

**Comment by yongshuai1573** [comment]
![image](https://user-images.githubusercontent.com/45225497/50669669-842c0580-1001-11e9-9d03-94200c078cc0.png)

**Comment by Webdiyer** [comment]
AspNetCorePager？没听过这个，应该是别人写的，这是MvcPagerCore的库，弄错了。

**Comment by yongshuai1573** [comment]
哦哦，那是NutGet里还没有上传是吧，晓得了，感谢。

**Comment by Webdiyer** [comment]
是的，上传后有些问题我又删除了，没来得及再更新。

**Comment by yongshuai1573** [comment]
嗯，晓得了，谢谢。祝您生活，工作愉快。

**Comment by Webdiyer** [comment]
客气了，谢谢！
